# Generated by Django 3.0.3 on 2020-02-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200210_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='author',
            name='inf_aut',
            field=models.TextField(blank=True, help_text='Enter a brief description of the author', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=18, verbose_name='ISBN'),
        ),
    ]
